USE MASTER
GO
IF DB_ID('QLKS') IS NOT NULL
	DROP DATABASE QLKS
GO
CREATE DATABASE QLKS
GO
USE QLKS
GO
CREATE TABLE KHACHHANG(
MAKH  NVARCHAR(255) PRIMARY KEY ,
TENKH NVARCHAR(255)
)

CREATE TABLE KHACHHANGCANHAN(
MAKHCN NVARCHAR(255)  PRIMARY KEY ,
TENKHCN NVARCHAR(255),
CMND NVARCHAR(255),
SDT NVARCHAR(255),
DIACHI NVARCHAR(255),
MADOAN NVARCHAR(255) 

)
CREATE TABLE DOANKHACH(
MADKH NVARCHAR(255)  PRIMARY KEY ,
TENDKH NVARCHAR(255)
)
CREATE TABLE DONVILUHANH(
MADV NVARCHAR(255) PRIMARY KEY,
TENDV NVARCHAR(255),
SDTDV NVARCHAR(255),
EMAILDV NVARCHAR(255)
)

CREATE TABLE NHANVIEN(
MANV NVARCHAR(255) PRIMARY KEY,
LOAINV NVARCHAR(255),
SDT NVARCHAR(255),
EMAIL NVARCHAR(255),
DIACHI NVARCHAR(255),
LUONG NVARCHAR(255)
)
CREATE TABLE DATPHONG(
MADP NVARCHAR(255) PRIMARY KEY,
MANV NVARCHAR(255),
NGAYNHAN NVARCHAR(255),
NGAYTRA NVARCHAR(255),
NGAYDATPHONG NVARCHAR(255),
LOAIPHONG NVARCHAR(255),
TRANGTHAI NVARCHAR(255),
MAKH NVARCHAR(255),
MADVLH NVARCHAR(255)
)

CREATE TABLE SANPHAMDICHVU(
MASP NVARCHAR(255) PRIMARY KEY,
TENSP NVARCHAR(255),
LOAISP NVARCHAR(255),
GIASP NVARCHAR(255),
DONVI NVARCHAR(255),
THONGTINSP NVARCHAR(255)
)

CREATE TABLE HOADON(
MAHD NVARCHAR(255) PRIMARY KEY,
NGAY NVARCHAR(255),
GIO NVARCHAR(255),
TRANGTHAI NVARCHAR(255),
TONGTIEN NVARCHAR(255),
PTTHANHTOAN NVARCHAR(255),
MANV NVARCHAR(255),
MALSDP NVARCHAR(255)
)

CREATE TABLE HOADONTRUCTUYEN(
MAHD NVARCHAR(255) PRIMARY KEY,
MAGIAODICH NVARCHAR(255),
LOAITHE NVARCHAR(255),
SOTHE NVARCHAR(255),
NGAYHETHAN NVARCHAR(255),
MABAOMAT NVARCHAR(255),
TENCHUTHE NVARCHAR(255)

)
CREATE TABLE PHIEUDANGKYTOUR(
MAPHIEUDK NVARCHAR(255) PRIMARY KEY,
THOIGIANKHOIHANH NVARCHAR(255),
NGAYDK NVARCHAR(255),
SONGUOITHAMGIA NVARCHAR(255),
DICHVUDUADON NVARCHAR(255),
YEUCAUDACBIET NVARCHAR(255),
KETQUADANGKY NVARCHAR(255),
MATOUR NVARCHAR(255)
)

CREATE TABLE TOUR(
MATOUR NVARCHAR(255) PRIMARY KEY,
THONGTINSP NVARCHAR(255),
LOAISP NVARCHAR(255),
GIASP NVARCHAR(255),
MADVLH NVARCHAR(255)
)
CREATE TABLE KHACHHANGTHAMGIATOUR(
MAKH NVARCHAR(255),
MAPHIEUDK NVARCHAR(255)
PRIMARY KEY (MAKH,MAPHIEUDK)
)
CREATE TABLE PHONG(
MAPHONG NVARCHAR(255) PRIMARY KEY,
LOAIPHONG NVARCHAR(255),
TRANGTHAIPHONG NVARCHAR(255)
)
CREATE TABLE THONGTINSUDUNGDICHVU(
MATT NVARCHAR(255) PRIMARY KEY,
MASP NVARCHAR(255),
MALSDP NVARCHAR(255),
MAHD NVARCHAR(255),
STT	NVARCHAR(255),
GIATHANH NVARCHAR(255),
SOLUONG NVARCHAR(255)

)

CREATE TABLE LICHSUDUNGPHONG(
MALSDP NVARCHAR(255) PRIMARY KEY,
MADP NVARCHAR(255),
MAPHONG NVARCHAR(255),
STT NVARCHAR(255),
NGAYNHAN NVARCHAR(255),
NGAYTRA NVARCHAR(255),

)
CREATE TABLE LICHSUDUNGDICHVU(
MAPHIEUDK NVARCHAR(255) PRIMARY KEY,
THOIGIANSUDUNG NVARCHAR(255),
NGAYDANGKY NVARCHAR(255),
YEUCAUDACBIET NVARCHAR(255),
MATTSDDV NVARCHAR(255),
)
ALTER TABLE KHACHHANGCANHAN
ADD CONSTRAINT FK_KHCN_KH
	FOREIGN KEY (MAKHCN)
	REFERENCES KHACHHANG,
    CONSTRAINT FK_KHCN_DK
	FOREIGN KEY (MADOAN)
	REFERENCES DOANKHACH

ALTER TABLE DOANKHACH
ADD CONSTRAINT FK_DK_KH
	FOREIGN KEY (MADKH)
	REFERENCES KHACHHANG

ALTER TABLE DATPHONG
ADD CONSTRAINT FK_DP_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG,
	CONSTRAINT FK_DP_NV
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN,
	CONSTRAINT FK_DVLH_NV
	FOREIGN KEY (MADVLH)
	REFERENCES DONVILUHANH

ALTER TABLE THONGTINSUDUNGDICHVU
ADD CONSTRAINT FK_TT_SP
	FOREIGN KEY (MASP)
	REFERENCES SANPHAMDICHVU,
	CONSTRAINT FK_TT_LSDP
	FOREIGN KEY (MALSDP)
	REFERENCES LICHSUDUNGPHONG,
	CONSTRAINT FK_TT_HD
	FOREIGN KEY (MAHD)
	REFERENCES HOADON
ALTER TABLE LICHSUDUNGDICHVU
ADD CONSTRAINT FK_LICH_DV
	FOREIGN KEY (MATTSDDV)
	REFERENCES THONGTINSUDUNGDICHVU
ALTER TABLE LICHSUDUNGPHONG
ADD CONSTRAINT FK_LS_DP
	FOREIGN KEY( MADP)
	REFERENCES DATPHONG,
	CONSTRAINT FK_SL_P
	FOREIGN KEY (MAPHONG)
	REFERENCES PHONG
ALTER TABLE HOADON 
ADD CONSTRAINT FK_HD_NV
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN,
	CONSTRAINT FK_HD_LSDP
	FOREIGN KEY (MALSDP)
	REFERENCES LICHSUDUNGPHONG
ALTER TABLE HOADONTRUCTUYEN
ADD CONSTRAINT FK_HDTT_HD
	FOREIGN KEY (MAHD)
	REFERENCES HOADON
ALTER TABLE PHIEUDANGKYTOUR
ADD CONSTRAINT FK_PDKT_T
	FOREIGN KEY (MATOUR)
	REFERENCES TOUR
ALTER TABLE KHACHHANGTHAMGIATOUR
ADD CONSTRAINT FK_KHTGT_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANGCANHAN,
	CONSTRAINT FK_KHTGT_PDKT
	FOREIGN KEY (MAPHIEUDK)
	REFERENCES PHIEUDANGKYTOUR
ALTER TABLE TOUR
ADD CONSTRAINT FK_T_DVLH
	FOREIGN KEY (MADVLH)
	REFERENCES DONVILUHANH

INSERT INTO PHONG (MAPHONG, LOAIPHONG, TRANGTHAIPHONG) VALUES(1,'Phong don', 'Trong');
INSERT INTO PHONG (MAPHONG, LOAIPHONG, TRANGTHAIPHONG) VALUES(2,'Phong doi', 'Trong');
INSERT INTO PHONG (MAPHONG, LOAIPHONG, TRANGTHAIPHONG) VALUES(3,'Phong doi', 'Trong');
INSERT INTO PHONG (MAPHONG, LOAIPHONG, TRANGTHAIPHONG) VALUES(4,'Phong doi', 'Trong');
INSERT INTO PHONG (MAPHONG, LOAIPHONG, TRANGTHAIPHONG) VALUES(5,'Phong don', 'Day');

INSERT INTO KHACHHANG (MAKH, TENKH) VALUES ('KH001', 'NGUYEN VAN AN');
INSERT INTO KHACHHANG (MAKH, TENKH) VALUES ('KH002', 'LE THI BINH');
INSERT INTO KHACHHANG (MAKH, TENKH) VALUES ('KH003', 'TRAN VAN CONG');
INSERT INTO KHACHHANG (MAKH, TENKH) VALUES ('KH004', 'NGUYEN THI DUNG');
INSERT INTO KHACHHANG (MAKH, TENKH) VALUES ('KH005', 'PHAN VAN HOANG');

INSERT INTO DATPHONG (MADP, MANV, NGAYNHAN, NGAYTRA, NGAYDATPHONG, LOAIPHONG, TRANGTHAI, MAKH, MADVLH)
VALUES ('DP001', NULL, '2023-05-09', '2023-05-12', '2023-05-08', 'Phòng Đơn', 'processing', 'KH001', NULL);
INSERT INTO DATPHONG (MADP, MANV, NGAYNHAN, NGAYTRA, NGAYDATPHONG, LOAIPHONG, TRANGTHAI, MAKH, MADVLH)
VALUES ('DP002', NULL, '2023-05-10', '2023-05-15', '2023-05-08', 'Phòng Đôi', 'processing', 'KH002', NULL);
INSERT INTO DATPHONG (MADP, MANV, NGAYNHAN, NGAYTRA, NGAYDATPHONG, LOAIPHONG, TRANGTHAI, MAKH, MADVLH)
VALUES ('DP003', NULL, '2023-05-11', '2023-05-13', '2023-05-08', 'Phòng Đơn', 'processing', 'KH003', NULL);
INSERT INTO DATPHONG (MADP, MANV, NGAYNHAN, NGAYTRA, NGAYDATPHONG, LOAIPHONG, TRANGTHAI, MAKH, MADVLH)
VALUES ('DP004', NULL, '2023-05-12', '2023-05-14', '2023-05-08', 'Phòng Đơn', 'processing', 'KH004', NULL);
INSERT INTO DATPHONG (MADP, MANV, NGAYNHAN, NGAYTRA, NGAYDATPHONG, LOAIPHONG, TRANGTHAI, MAKH, MADVLH)
VALUES ('DP005', NULL, '2023-05-13', '2023-05-16', '2023-05-08', 'Phòng Đôi', 'check in', 'KH005', NULL);

