USE MASTER
GO
IF DB_ID('QLKS') IS NOT NULL
	DROP DATABASE QLKS
GO
CREATE DATABASE QLKS
GO
USE QLKS
GO
CREATE TABLE KHACHHANG(
MAKH  NVARCHAR PRIMARY KEY 
)

CREATE TABLE KHACHHANGCANHAN(
MAKHCN NVARCHAR  PRIMARY KEY ,
TENKHCN NVARCHAR,
CMND NVARCHAR,
SDT NVARCHAR,
DIACHI NVARCHAR,
MADOAN NVARCHAR 

)
CREATE TABLE DOANKHACH(
MADKH NVARCHAR  PRIMARY KEY ,
TENDKH NVARCHAR
)
CREATE TABLE DONVILUHANH(
MADV NVARCHAR PRIMARY KEY,
TENDV NVARCHAR,
SDTDV NVARCHAR,
EMAILDV NVARCHAR
)

CREATE TABLE NHANVIEN(
MANV NVARCHAR PRIMARY KEY,
LOAINV NVARCHAR,
SDT NVARCHAR,
EMAIL NVARCHAR,
DIACHI NVARCHAR,
LUONG NVARCHAR
)
CREATE TABLE DATPHONG(
MADP NVARCHAR PRIMARY KEY,
MANV NVARCHAR,
NGAYNHAN NVARCHAR,
NGAYTRA NVARCHAR,
NGAYDATPHONG NVARCHAR,
LOAIPHONG NVARCHAR,
TRANGTHAI NVARCHAR,
MAKH NVARCHAR,
MADVLH NVARCHAR
)

CREATE TABLE SANPHAMDICHVU(
MASP NVARCHAR PRIMARY KEY,
TENSP NVARCHAR,
LOAISP NVARCHAR,
GIASP NVARCHAR,
DONVI NVARCHAR,
THONGTINSP NVARCHAR
)

CREATE TABLE HOADON(
MAHD NVARCHAR PRIMARY KEY,
NGAY NVARCHAR,
GIO NVARCHAR,
TRANGTHAI NVARCHAR,
TONGTIEN NVARCHAR,
PTTHANHTOAN NVARCHAR,
MANV NVARCHAR,
MALSDP NVARCHAR
)

CREATE TABLE HOADONTRUCTUYEN(
MAHD NVARCHAR PRIMARY KEY,
MAGIAODICH NVARCHAR,
LOAITHE NVARCHAR,
SOTHE NVARCHAR,
NGAYHETHAN NVARCHAR,
MABAOMAT NVARCHAR,
TENCHUTHE NVARCHAR

)
CREATE TABLE PHIEUDANGKYTOUR(
MAPHIEUDK NVARCHAR PRIMARY KEY,
THOIGIANKHOIHANH NVARCHAR,
NGAYDK NVARCHAR,
SONGUOITHAMGIA NVARCHAR,
DICHVUDUADON NVARCHAR,
YEUCAUDACBIET NVARCHAR,
KETQUADANGKY NVARCHAR,
MATOUR NVARCHAR
)

CREATE TABLE TOUR(
MATOUR NVARCHAR PRIMARY KEY,
THONGTINSP NVARCHAR,
LOAISP NVARCHAR,
GIASP NVARCHAR,
MADVLH NVARCHAR
)
CREATE TABLE KHACHHANGTHAMGIATOUR(
MAKH NVARCHAR,
MAPHIEUDK NVARCHAR
PRIMARY KEY (MAKH,MAPHIEUDK)
)
CREATE TABLE PHONG(
MAPHONG NVARCHAR PRIMARY KEY,
LOAIPHONG NVARCHAR,
TRANGTHAIPHONG NVARCHAR
)
CREATE TABLE THONGTINSUDUNGDICHVU(
MATT NVARCHAR PRIMARY KEY,
MASP NVARCHAR,
MALSDP NVARCHAR,
MAHD NVARCHAR,
STT	NVARCHAR,
GIATHANH NVARCHAR,
SOLUONG NVARCHAR

)

CREATE TABLE LICHSUDUNGPHONG(
MALSDP NVARCHAR PRIMARY KEY,
MADP NVARCHAR,
MAPHONG NVARCHAR,
STT NVARCHAR,
NGAYNHAN NVARCHAR,
NGAYTRA NVARCHAR,

)
CREATE TABLE LICHSUDUNGDICHVU(
MAPHIEUDK NVARCHAR PRIMARY KEY,
THOIGIANSUDUNG NVARCHAR,
NGAYDANGKY NVARCHAR,
YEUCAUDACBIET NVARCHAR,
MATTSDDV NVARCHAR,
)
ALTER TABLE KHACHHANGCANHAN
ADD CONSTRAINT FK_KHCN_KH
	FOREIGN KEY (MAKHCN)
	REFERENCES KHACHHANG,
    CONSTRAINT FK_KHCN_DK
	FOREIGN KEY (MADOAN)
	REFERENCES DOANKHACH

ALTER TABLE DOANKHACH
ADD CONSTRAINT FK_DK_KH
	FOREIGN KEY (MADKH)
	REFERENCES KHACHHANG

ALTER TABLE DATPHONG
ADD CONSTRAINT FK_DP_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG,
	CONSTRAINT FK_DP_NV
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN,
	CONSTRAINT FK_DVLH_NV
	FOREIGN KEY (MADVLH)
	REFERENCES DONVILUHANH

ALTER TABLE THONGTINSUDUNGDICHVU
ADD CONSTRAINT FK_TT_SP
	FOREIGN KEY (MASP)
	REFERENCES SANPHAMDICHVU,
	CONSTRAINT FK_TT_LSDP
	FOREIGN KEY (MALSDP)
	REFERENCES LICHSUDUNGPHONG,
	CONSTRAINT FK_TT_HD
	FOREIGN KEY (MAHD)
	REFERENCES HOADON
ALTER TABLE LICHSUDUNGDICHVU
ADD CONSTRAINT FK_LICH_DV
	FOREIGN KEY (MATTSDDV)
	REFERENCES THONGTINSUDUNGDICHVU
ALTER TABLE LICHSUDUNGPHONG
ADD CONSTRAINT FK_LS_DP
	FOREIGN KEY( MADP)
	REFERENCES DATPHONG,
	CONSTRAINT FK_SL_P
	FOREIGN KEY (MAPHONG)
	REFERENCES PHONG
ALTER TABLE HOADON 
ADD CONSTRAINT FK_HD_NV
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN,
	CONSTRAINT FK_HD_LSDP
	FOREIGN KEY (MALSDP)
	REFERENCES LICHSUDUNGPHONG
ALTER TABLE HOADONTRUCTUYEN
ADD CONSTRAINT FK_HDTT_HD
	FOREIGN KEY (MAHD)
	REFERENCES HOADON
ALTER TABLE PHIEUDANGKYTOUR
ADD CONSTRAINT FK_PDKT_T
	FOREIGN KEY (MATOUR)
	REFERENCES TOUR
ALTER TABLE KHACHHANGTHAMGIATOUR
ADD CONSTRAINT FK_KHTGT_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANGCANHAN,
	CONSTRAINT FK_KHTGT_PDKT
	FOREIGN KEY (MAPHIEUDK)
	REFERENCES PHIEUDANGKYTOUR
ALTER TABLE TOUR
ADD CONSTRAINT FK_T_DVLH
	FOREIGN KEY (MADVLH)
	REFERENCES DONVILUHANH

